# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '网易新闻' do

pod 'MBProgressHUD'
pod 'JZNavigationExtension'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDCycleScrollView'


end

target '网易新闻Tests' do

end

target '网易新闻UITests' do

end

